import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { Users, Car, Route, Activity, XCircle } from "lucide-react";
type Stats={passengers:number;drivers:number;trips:number;activeTrips:number};type Trip={id:string;origin:string;destination:string;status:string;fare:number|null;payment_status:string;created_at:string};
export default function AdminDashboard(){
 const[stats,setStats]=useState<Stats>({passengers:0,drivers:0,trips:0,activeTrips:0});const[trips,setTrips]=useState<Trip[]>([]);const[message,setMessage]=useState("");
 async function load(){const[p,d,t,a]=await Promise.all([supabase.from("profiles").select("id",{count:"exact",head:true}).eq("role","passenger"),supabase.from("drivers").select("id",{count:"exact",head:true}),supabase.from("trips").select("id",{count:"exact",head:true}),supabase.from("trips").select("id",{count:"exact",head:true}).in("status",["requested","accepted","driver_arriving","in_progress"])]);setStats({passengers:p.count||0,drivers:d.count||0,trips:t.count||0,activeTrips:a.count||0});const recent=await supabase.from("trips").select("id,origin,destination,status,fare,payment_status,created_at").order("created_at",{ascending:false}).limit(20);if(recent.error)setMessage(recent.error.message);else setTrips(recent.data||[])}
 useEffect(()=>{load();const c=supabase.channel("admin-trip-feed").on("postgres_changes",{event:"*",schema:"public",table:"trips"},()=>load()).subscribe();return()=>{supabase.removeChannel(c)}},[]);
 async function cancelTrip(id:string){const{error}=await supabase.from("trips").update({status:"cancelled"}).eq("id",id);if(error)setMessage(error.message);else{setMessage("Viagem cancelada.");load()}}
 return <section className="ops-shell"><div className="ops-hero"><div><span>HORIZONTE BONINAS · OPERAÇÕES</span><h1>Painel de controlo</h1><p>Monitore passageiros, motoristas e viagens numa única visão.</p></div><div className="ops-live"><i/> LIVE</div></div><div className="ops-stats"><div><Users/><b>{stats.passengers}</b><span>Passageiros</span></div><div><Car/><b>{stats.drivers}</b><span>Motoristas</span></div><div><Route/><b>{stats.trips}</b><span>Viagens</span></div><div><Activity/><b>{stats.activeTrips}</b><span>Activas</span></div></div>{message&&<div className="ops-message">{message}</div>}<div className="ops-section-title"><span>OPERAÇÕES</span><h2>Viagens recentes</h2></div><div className="ops-trip-list">{trips.map(t=><article className="ops-trip" key={t.id}><div className="ops-trip-icon"><Route size={20}/></div><div className="ops-trip-main"><b>{t.origin} → {t.destination}</b><span>{t.status} · pagamento: {t.payment_status}</span><small>{t.fare?Number(t.fare).toLocaleString("pt-AO")+" Kz":"Tarifa pendente"}</small></div>{["requested","accepted","driver_arriving","in_progress"].includes(t.status)&&<button className="ops-cancel" onClick={()=>cancelTrip(t.id)}><XCircle size={15}/> Cancelar</button>}</article>)}</div></section>;
}