import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { Car, Power, Navigation, CheckCircle2, Clock3 } from "lucide-react";
type Trip={id:string;origin:string;destination:string;status:string;fare:number|null;payment_method:string;created_at:string};
export default function DriverDashboard(){
 const[driverId,setDriverId]=useState("");const[status,setStatus]=useState("offline");const[trips,setTrips]=useState<Trip[]>([]);const[message,setMessage]=useState("");
 async function load(){const{data:s}=await supabase.auth.getSession();const uid=s.session?.user.id;if(!uid)return;const{data:d}=await supabase.from("drivers").select("id,status").eq("id",uid).maybeSingle();if(d){setDriverId(d.id);setStatus(d.status)}const{data:t}=await supabase.from("trips").select("id,origin,destination,status,fare,payment_method,created_at").in("status",["requested","accepted","driver_arriving","in_progress"]).order("created_at",{ascending:false}).limit(20);if(t)setTrips(t)}
 useEffect(()=>{load();const c=supabase.channel("driver-trip-feed").on("postgres_changes",{event:"*",schema:"public",table:"trips"},()=>load()).subscribe();return()=>{supabase.removeChannel(c)}},[]);
 async function setDriverStatus(value:string){if(!driverId){setMessage("Este utilizador ainda não está registado como motorista.");return}const{error}=await supabase.from("drivers").update({status:value}).eq("id",driverId);if(error)setMessage(error.message);else{setStatus(value);setMessage(value==="available"?"Está disponível para novas viagens.":"Ficou offline.")}}
 async function updateTrip(id:string,next:string){const{error}=await supabase.from("trips").update({driver_id:driverId,status:next}).eq("id",id);if(error)setMessage(error.message);else{setMessage("Viagem atualizada.");await load()}}
 return <section className="ops-shell"><div className="ops-hero"><div><span>HORIZONTE BONINAS · MOTORISTA</span><h1>Central de viagens</h1><p>Receba pedidos, aceite viagens e actualize o estado em tempo real.</p></div><div className={"ops-online "+(status==="available"?"on":"")}><i/><b>{status==="available"?"Disponível":"Offline"}</b></div></div><div className="ops-status"><div><Power size={18}/><div><b>Estado do motorista</b><small>Controla quando pode receber pedidos.</small></div></div><div><button className="ops-primary" onClick={()=>setDriverStatus("available")}>Ficar disponível</button><button className="ops-secondary" onClick={()=>setDriverStatus("offline")}>Ficar offline</button></div></div>{message&&<div className="ops-message">{message}</div>}<div className="ops-section-title"><span>PEDIDOS</span><h2>Viagens disponíveis e activas</h2></div><div className="ops-trip-list">{trips.length===0?<div className="ops-empty"><Car size={30}/><h3>Nenhuma viagem neste momento</h3><p>Novos pedidos aparecerão automaticamente.</p></div>:trips.map(t=><article className="ops-trip" key={t.id}><div className="ops-trip-icon"><Car size={20}/></div><div className="ops-trip-main"><b>{t.origin} → {t.destination}</b><span><Clock3 size={13}/> {t.status} · {t.payment_method}</span><small>{t.fare?Number(t.fare).toLocaleString("pt-AO")+" Kz":"Tarifa pendente"}</small></div><div className="ops-trip-action">{t.status==="requested"&&<button onClick={()=>updateTrip(t.id,"accepted")}>Aceitar</button>}{t.status==="accepted"&&<button onClick={()=>updateTrip(t.id,"driver_arriving")}>A caminho</button>}{t.status==="driver_arriving"&&<button onClick={()=>updateTrip(t.id,"in_progress")}>Iniciar</button>}{t.status==="in_progress"&&<button onClick={()=>updateTrip(t.id,"completed")}><CheckCircle2 size={15}/> Concluir</button>}</div></article>)}</div></section>;
}