import{useEffect,useState}from"react";import{MapPin,Car,ShieldCheck,Clock3,ArrowRight,LogIn,Menu,Navigation,Package,CalendarDays,Star,ChevronRight}from"lucide-react";import{ReactNode}from"react";import{supabase}from"./lib/supabase";import PassengerAccess from"./components/PassengerAccess";import PassengerDashboard from"./components/PassengerDashboard";import DriverDashboard from"./components/DriverDashboard";import AdminDashboard from"./components/AdminDashboard";
type Route={id:string;origin:string;destination:string;base_fare:number;estimated_minutes:number};
const services=[{icon:<Car/>,title:"Boninas Táxi",text:"Transporte personalizado com conforto e atendimento dedicado."},{icon:<Navigation/>,title:"Horizonte Boninas",text:"Viagens programadas entre Sumbe e Luanda, todos os dias."},{icon:<Package/>,title:"Encomendas",text:"Seguras • Rápidas • Com Responsabilidade."}];
export default function App(){const[routes,setRoutes]=useState<Route[]>([]);const[session,setSession]=useState<any>(null);const[role,setRole]=useState<string|null>(null);const[showLogin,setShowLogin]=useState(false);const[mobile,setMobile]=useState(false);
async function loadSession(s:any){setSession(s);if(s?.user?.id){const{data}=await supabase.from("profiles").select("role").eq("id",s.user.id).maybeSingle();setRole(data?.role||"passenger")}else setRole(null)}
useEffect(()=>{supabase.auth.getSession().then(({data})=>loadSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>loadSession(s));supabase.from("routes").select("*").eq("active",true).order("origin").then(({data})=>setRoutes((data||[])as Route[]));return()=>subscription.unsubscribe()},[]);
if(session&&role==="admin")return <><RoleHeader label="Administração" signOut={()=>supabase.auth.signOut()}/><AdminDashboard/></>;
if(session&&role==="driver")return <><RoleHeader label="Motorista" signOut={()=>supabase.auth.signOut()}/><DriverDashboard/></>;
if(session)return <><RoleHeader label="Passageiro" signOut={()=>supabase.auth.signOut()}/><PassengerDashboard/></>;
return <div className="app"><header className="topbar"><a className="brand brand-logo" href="#"><div className="logo-mark"><span>HB</span></div><div><strong>HORIZONTE <b>BONINAS</b></strong><span>Transporte Personalizado</span></div></a><nav className={mobile?"mobile-open":""}><a href="#servicos">Serviços</a><a href="#rotas">Rotas</a><a href="#seguranca">Segurança</a><button className="outline" onClick={()=>setShowLogin(true)}><LogIn size={16}/> Entrar</button></nav><button className="menu-button" onClick={()=>setMobile(!mobile)}><Menu/></button></header>
<main><section className="hero hero-app"><div className="hero-copy"><span className="eyebrow pink">TRANSPORTE PERSONALIZADO</span><h1>Mais que uma viagem,<br/><em>é o seu destino</em><br/>em boas mãos.</h1><p>Reserve viagens, acompanhe o percurso e tenha uma experiência de mobilidade simples, segura e personalizada.</p><div className="actions"><button className="primary" onClick={()=>setShowLogin(true)}>Solicitar viagem <ArrowRight size={18}/></button><a className="secondary" href="#rotas">Explorar rotas</a></div><div className="trust-row"><span><ShieldCheck size={16}/> Segurança</span><span><Clock3 size={16}/> Pontualidade</span><span><Car size={16}/> Conforto</span></div></div><div className="booking-shell"><div className="booking-card booking-modern"><div className="card-top"><span className="status-dot"></span><div><strong>Solicitar transporte</strong><small>Escolha a sua viagem</small></div></div><label><span>De</span><div className="field"><MapPin size={18}/><select><option>Sumbe</option><option>Luanda</option></select></div></label><label><span>Para</span><div className="field"><Navigation size={18}/><select><option>Luanda</option><option>Sumbe</option></select></div></label><label><span>Data e hora</span><div className="field"><CalendarDays size={18}/><input type="datetime-local"/></div></label><button className="primary full" onClick={()=>setShowLogin(true)}>Continuar <ChevronRight size={18}/></button><small className="muted">Entre na sua conta para confirmar a solicitação.</small></div></div></section>
<section id="servicos" className="section section-soft"><div className="section-head"><div><span className="eyebrow">NOSSOS SERVIÇOS</span><h2>Escolha como quer viajar</h2></div></div><div className="cards">{services.map((s,i)=><article className={"card service-card "+(i===0?"active":"")} key={s.title}><div className="icon">{s.icon}</div><div><h3>{s.title}</h3><p>{s.text}</p></div><ChevronRight className="card-arrow" size={19}/></article>)}</div></section>
<section id="rotas" className="section"><div className="section-head"><div><span className="eyebrow pink">ROTAS PRINCIPAIS</span><h2>Sumbe ⇄ Luanda</h2><p className="section-sub">Todos os dias, com horários definidos para facilitar a sua viagem.</p></div></div><div className="route-feature"><div className="route-map"><div className="map-grid"></div><div className="map-line"></div><div className="map-pin pin-a"><MapPin/></div><div className="map-pin pin-b"><MapPin/></div><span className="city city-a">SUMBE</span><span className="city city-b">LUANDA</span></div><div className="route-info"><span className="route-badge">TODOS OS DIAS</span><h3>SUMBE <strong>⇄</strong> LUANDA</h3><div className="schedule"><div><span>Partida</span><strong>06H</strong></div><div><span>Partida</span><strong>14H</strong></div></div><div className="pickup"><MapPin size={17}/><span><b>No Sumbe</b> Buscamos em sua casa</span></div><div className="pickup"><MapPin size={17}/><span><b>Em Luanda</b> Pumangol do Benfica / Junto ao KFC</span></div><button className="primary full" onClick={()=>setShowLogin(true)}>Reservar esta rota <ArrowRight size={17}/></button></div></div>{routes.length>0&&<div className="route-grid compact">{routes.map(r=><div className="route" key={r.id}><MapPin size={19}/><div><strong>{r.origin} → {r.destination}</strong><span>{r.estimated_minutes?"~"+r.estimated_minutes+" min":"Disponível mediante reserva"}</span></div></div>)}</div>}</section>
<section id="seguranca" className="trust trust-modern"><div className="trust-icon"><ShieldCheck size={28}/></div><div><span className="eyebrow">CONFIANÇA EM CADA ETAPA</span><h3>Uma plataforma feita para acompanhar a sua viagem</h3><p>Passageiros, motoristas, viagens, reservas, encomendas, pagamentos e avaliações organizados numa única experiência.</p></div><div className="trust-stat"><Star fill="currentColor" size={18}/><strong>Experiência</strong><span>Conforto • Segurança • Pontualidade</span></div></section></main>
<footer><div className="footer-brand"><div className="logo-mark"><span>HB</span></div><div><strong>HORIZONTE BONINAS</strong><span>Transporte Personalizado</span></div></div><span>© Horizonte Boninas</span></footer>{showLogin&&<div className="modal-backdrop" onClick={()=>setShowLogin(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowLogin(false)}>×</button><PassengerAccess onSuccess={()=>setShowLogin(false)}/></div></div>}</div>}
function RoleHeader({label,signOut}:{label:string,signOut:()=>void}){return <header className="app-header"><div className="brand"><div className="logo-mark"><span>HB</span></div><div><strong>HORIZONTE BONINAS</strong><span>{label}</span></div></div><button className="outline" onClick={signOut}>Sair</button></header>}